mitodl/open-edx-plugins

- poetry.lock
- pyproject.toml
#14 , #15 
- Tightens the boundary for the Django version to be used (`above 2.0 & below 4.0`) 
- Updates the poetry config
- Generate new plugin builds for `ol-openedx-logging` & `ol-openedx-sentry` and install them into the Maple release of edX and make sure that things work fine.
> build: update the Django versions support(3.2)

- src/ol_openedx_canvas_integration/README.rst
https://github.com/mitodl/open-edx-plugins/issues/5
- Adds the usage & installation instruction documentation for `Canvas Integration` plugin
- Try to follow the instructions on the documentation and see if the plugin works
We recently created a new Plugin `Canvas Integration` in https://github.com/mitodl/open-edx-plugins/pull/8. But we didn't add the documentation in that at that moment. This is a follow-up PR for adding that documentation
> docs: Add documentation for Canvas Integration plugin

- src/ol_openedx_canvas_integration/README.rst
- src/ol_openedx_rapid_response_reports/README.rst
None
- Fixes the references in the READMEs.
Our plugin PRs were merged first and then the platform counterparts which were squashed and the commit hashes changed with new commit. So, This PR just fixes that.
Just verify the links point to the correct URLs.
> fix: commit urls associated with platform

- src/ol_openedx_canvas_integration/README.rst
- src/ol_openedx_rapid_response_reports/README.rst
Recently noticed, the commits mentioned in `README.rst` were picked from the `mitx/maple` branch after the relevant PRs(https://github.com/mitodl/edx-platform/pull/274, https://github.com/mitodl/edx-platform/pull/275) were merged there believing they will persist as part of that branch. But recently these commits were removed from `mitx/maple` history showing these commit doesn't belong to any branch.
To fix: Since the PRs for both have only one commit each, So, I have now referred to the commits that are associated with the PR itself & not the `mitx/maple`.
> docs: update commit references for Rapid Response, Canvas Plugin

- src/ol_openedx_course_export/.coveragerc
- src/ol_openedx_course_export/BUILD
- src/ol_openedx_course_export/CHANGELOG.rst
- src/ol_openedx_course_export/LICENSE.txt
- src/ol_openedx_course_export/MANIFEST.in
- src/ol_openedx_course_export/README.rst
- src/ol_openedx_course_export/__init__.py
- src/ol_openedx_course_export/app.py
- src/ol_openedx_course_export/constants.py
- src/ol_openedx_course_export/s3_client.py
- src/ol_openedx_course_export/settings/BUILD
- src/ol_openedx_course_export/settings/common.py
- src/ol_openedx_course_export/settings/production.py
- src/ol_openedx_course_export/urls.py
- src/ol_openedx_course_export/utils.py
- src/ol_openedx_course_export/views.py
#27 
- Add basic architecture of a django plugin for edX
- Adds a new API to generate OLX course exports and upload to s3
-  Generate a build for the package. We are using 'Pants' for that. Run `./pants package ::` in the main directory in the terminal which will generate many `.tar.gz & .whl` packages for you.
- Run `make studio-shell` and install `ol-openedx-coruse-course.*` (.gz or .whl)
-  You need to set the configuration values for the S3/AWS. e.g. set proper values for `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `COURSE_IMPORT_EXPORT_BUCKET`. (All of these can be set in `private.py`)
- You will need a django admin user to test this API otherwise you would not be authorized
- Check access by calling the API without `Authorization` header and notice `400 with authorization error …
> feat: Add course export s3 plugin

- .pre-commit-config.yaml
- src/ol_openedx_course_export/s3_client.py
- src/ol_openedx_course_export/tasks.py
- src/ol_openedx_course_export/urls.py
- src/ol_openedx_course_export/views.py
https://github.com/mitodl/open-edx-plugins/issues/27
- As the next part of the course export enhancement we attempted running the course export in separate celery tasks to avoid any timeout issues that we see. (This is something similar that the existing course export functionality is doing, and we intend to follow the same track in our plugin)
- Trying to implement course export tasks and structure that would match Open edX's local course export but support the celery tasks for exporting courses to s3.
- Add a new API to `GET` the status of the running tasks by course key & task ID
- Install the plugin through the steps mentioned in the Readme of the plugin (Or the steps mentioned in https://github.com/mitodl/open-edx-plugins/pull/29)
- Configure the required AWS keys mentioned in …
> perf: enhance course export to use celery tasks

- src/ol_openedx_canvas_integration/tasks.py
#37 
- Replaces the usage of deprecated `celery.task` with `celery.shared_task` (More details on the associated ticket)
- First of all, you should get to [mitx/maple](https://github.com/mitodl/edx-platform/tree/mitx/maple) branch of edx-platform
- Install this plugin as per the docs mentioned in https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_canvas_integration
- Make sure that the celery tasks are being called properly.
> chore: fix deprecated celery task

- src/ol_openedx_checkout_external/.coveragerc
- src/ol_openedx_checkout_external/BUILD
- src/ol_openedx_checkout_external/CHANGELOG.rst
- src/ol_openedx_checkout_external/LICENSE.txt
- src/ol_openedx_checkout_external/MANIFEST.in
- src/ol_openedx_checkout_external/README.rst
- src/ol_openedx_checkout_external/__init__.py
- src/ol_openedx_checkout_external/app.py
- src/ol_openedx_checkout_external/exceptions.py
- src/ol_openedx_checkout_external/settings/BUILD
- src/ol_openedx_checkout_external/settings/common.py
- src/ol_openedx_checkout_external/settings/production.py
- src/ol_openedx_checkout_external/urls.py
- src/ol_openedx_checkout_external/views.py
#28 
- Adds an API to map SKU to external checkout pages.
- Adds a new configuration to set custom external checkout URL for the marketing site
Based on the above, The API works as the alternate to the built-in eCommerce of edX by taking the upgrade URLs request in place of edX's eCommerce, customizes the URL w.r.t the external website with added params, and redirecting the user to that.
You can test the API with steps mentioned in the README (https://github.com/mitodl/open-edx-plugins/tree/arslan/28-external-checkout/src/ol_openedx_checkout_external)
_for TLDR;_
1) Generate & install the plugin with [common instructions](https://github.com/mitodl/open-edx-plugins/tree/arslan/28-external-checkout/src/ol_openedx_checkout_external#installation)
2) In `private.py` set …
> feat: add external checkout api plugin

- src/ol_openedx_rapid_response_reports/BUILD
- src/ol_openedx_rapid_response_reports/README.rst
- src/ol_openedx_rapid_response_reports/app.py
- src/ol_openedx_rapid_response_reports/context_api.py
- src/ol_openedx_rapid_response_reports/settings/BUILD
- src/ol_openedx_rapid_response_reports/settings/production.py
- src/ol_openedx_rapid_response_reports/templates/BUILD
- src/ol_openedx_rapid_response_reports/templates/rapid_response.html
#50 
- Adds settings for templates based on pants
- Adds templates for rapid response reports
- Updates the context_api to support context that the `Instructor dashboard` can understand
- Add settings for serving templates through pants
- Updates dependencies for templates
(For installation steps you can look at the plugin's readme file -- Also note that you will need to restart your lms e.g. `make lms-restart` once you install the plugin)
- Just install the plugin and it should work without any cherry-pick as mentioned in README.
- You should be able to load the `Rapid Responses` tab and download the reports
- After the plugin is installed we will need to compile assets(`make lms-static`) otherwise we might see missing assets/JS errors and things might not work properly.
The `Rapid …
> feat: serve rapid_response_reports assets and add instructor tab from plugin

- src/ol_openedx_canvas_integration/BUILD
- src/ol_openedx_canvas_integration/README.rst
- src/ol_openedx_canvas_integration/app.py
- src/ol_openedx_canvas_integration/context_api.py
- src/ol_openedx_canvas_integration/settings/production.py
- src/ol_openedx_canvas_integration/static/js/BUILD
- src/ol_openedx_canvas_integration/static/js/canvas_integration.js
- src/ol_openedx_canvas_integration/templates/BUILD
- src/ol_openedx_canvas_integration/templates/canvas_integration.html
#13 
- Integrations the context api
- Adds the assets within the plugin
- adds configurations to serve the assets from the plugin
- will add configurations for pants build
- Setup edx-platform on nutmeg release
- cherry-pick the commit (A shortened version of the commit will be added once the PR is finalized because the current cherry-pick mentioned in this plugin's readme has all the things that won't be needed after this migration but some will still be there)
- Install the plugin
- Setting up edx-platform on Nutmeg
- We might need to compile assets(`make lms-static`) once this plugin is released and installed on the platform. Otherwise we might notice assets issues like we used to face in past.
When we added this plugin in the first place, edX won't support serving the assets right …
> feat: serve assets from plugin - nutmeg support

- src/ol_openedx_checkout_external/BUILD
- src/ol_openedx_checkout_external/settings/production.py
None (When the checkout plugin was deployed we noticed that the configuration added by the plugin was not getting picked up in the actual edX environment)
- loads the configuration values from the extended edX settings.
Nothing specific to test but it should load the configuration value in an actual edX instance.
I've bumped the version for this and we need to update and push a new release for this `ol-openedx-checkout-external` to PyPI followed by a rebuild of our edX MITxOnline-QA instance. @rhysyngsun @blarghmatey
> fix: load configuration from env_tokens for checkout plugin

- src/ol_openedx_canvas_integration/BUILD
- src/ol_openedx_canvas_integration/context_api.py
None - This is basically the implementation of https://github.com/mitodl/edx-platform/pull/266/files from platform to plugin
- Adds a check to show the Canvas tab only if there is an Associated Canvas Course ID set in the course through studio advanced settings.
- Follow the setup steps for Canvas
- Open any course that has no Canvas course id (Canvas tab shouldn't be shown)
- Now, go to Advanced settings for the course and set `Canvas Course ID` and reload the course (The Canvas tab should now be shown)
> Enhancement: Don't show Canvas tab if no associated Canvas Course ID is set

- .pre-commit-config.yaml
- src/ol_openedx_canvas_integration/BUILD
- src/ol_openedx_canvas_integration/context_api.py
None, https://sentry.io/organizations/mit-office-of-digital-learning/issues/3317544672/?project=1757731&referrer=slack - When we moved assets to the plugin we started seeing SuspeciousPath error because it won't accept JS file path from outside of the MEDIA_ROOT.
- Inspired by Rapid Response xBlock - It adds the JS bytes to the fragment.
The Canvas Plugin should work without error, The Canvas tab should show.
(Optional)
(Optional)
(Optional)
> fix: load JS as bytes and add to fragment

- src/ol_openedx_checkout_external/BUILD
- src/ol_openedx_checkout_external/views.py
https://github.com/mitodl/mitxonline/issues/610
Quotes the course id before adding it to the query parameters in the redirect URL. This is needed because course IDs in edX contain reserved chars e.g. `+`. When the GET API in the marketing application gets the parameters it's then converted into a space that ends up not finding the course.
However, this could have been done on the marketing site using `quote_plus` but I figured it would be better to just `quote`
it is in the plugins so that all the calling applications don't have to `quote_plus` the course Ids from the GET query params.
Currently, if the course id is `course-v1:MIT+MIT_GT_0001+1` it turns into `course-v1:MIT MIT_GT_0001 1` when we get it through request GET params.
For ref, take a look at …
> fix: quote course id before adding into redirect URL params

- src/ol_openedx_checkout_external/README.rst
None
Updates the readme for `external-checkout` plugin to include the conditions for SKUs. e.g. The Course Mode should be present with an SKU value and SKU value should be unique.
Just check README.
> docs: update external checkout readme to include SKUs conditions

- src/ol_openedx_canvas_integration/api.py
https://github.com/mitodl/edx-platform/issues/298
- Refactors the usage of `graded_subsections_by_format` to be called like a function.
- Clicking `Push all MITs grades to canvas` should push the grades to canvas.
- In response to some recent changes in the platform, [here](https://github.com/openedx/edx-platform/commit/a162140492d256be7cde5a53cb24ba221bc5cf5b#diff-f0d17d91bec07c249a69bfeb1b4be40078e8c433136af33644f429eeddcab9b3L74-R86)
> fix: use subsection format function instead of property

- src/ol_openedx_course_structure_api/.coveragerc
- src/ol_openedx_course_structure_api/BUILD
- src/ol_openedx_course_structure_api/CHANGELOG.rst
- src/ol_openedx_course_structure_api/LICENSE.txt
- src/ol_openedx_course_structure_api/MANIFEST.in
- src/ol_openedx_course_structure_api/README.rst
- src/ol_openedx_course_structure_api/__init__.py
- src/ol_openedx_course_structure_api/app.py
- src/ol_openedx_course_structure_api/settings/BUILD
- src/ol_openedx_course_structure_api/settings/common.py
- src/ol_openedx_course_structure_api/settings/production.py
- src/ol_openedx_course_structure_api/urls.py
- src/ol_openedx_course_structure_api/views.py
https://github.com/mitodl/open-edx-plugins/issues/110
This adds an API in LMS to retrieve the JSON representation of course structure. The management command for this can be found [here](https://github.com/openedx/edx-platform/blob/master/lms/djangoapps/courseware/management/commands/dump_course_structure.py)
endpoint: api/course-structure/v0/<course id>/ (requires admin access)
-  An open edX instance running on local (tutor or devstack)
- Setup a course in Studio (e.g. tutor http://studio.local.overhang.io/course/course-v1:edX+DemoX+Demo_Course )
- Give your account admin access
devstack
-  Generate and install the plugin following [these steps](https://github.com/mitodl/open-edx-plugins/blob/f3c2e99f6828eaaf892e4e7705b17077d5b036c5/src/ol_openedx_course_structure_api/README.rst#installa …
> feat: add course-structure-api plugin

- src/ol_openedx_course_structure_api/BUILD
- src/ol_openedx_course_structure_api/__init__.py
- src/ol_openedx_course_structure_api/views.py
https://github.com/mitodl/open-edx-plugins/issues/110
This PR fixes ImportError for `olive` open edx instance (e.g. xpro) https://mit-office-of-digital-learning.sentry.io/issues/?project=1730882&referrer=sidebar
```
cannot import name 'dump_block' from 'lms.djangoapps.courseware.management.commands.dump_course_structure' (/openedx/edx-platform/./lms/djangoapps/courseware/management/commands/dump_course_structure.py
```
In older versions of open edx like `olive` it still uses the old function name `dump_module` in [this file](https://github.com/openedx/edx-platform/blob/open-release/olive.master/lms/djangoapps/courseware/management/commands/dump_course_structure.py#L81). But `dump_module` has renamed to `dump_block` in [release-2023-03-08-14.35](https://github.com/openedx/edx-platform/relea …
> fix ImportError on dump_block for olive release 

- src/edx_sysadmin/BUILD
- src/edx_sysadmin/api/urls.py
- src/edx_sysadmin/urls.py
- src/ol_openedx_canvas_integration/BUILD
- src/ol_openedx_canvas_integration/context_api.py
- src/ol_openedx_canvas_integration/templates/canvas_integration.html
- src/ol_openedx_canvas_integration/urls.py
- src/ol_openedx_canvas_integration/views.py
- src/ol_openedx_rapid_response_reports/BUILD
- src/ol_openedx_rapid_response_reports/context_api.py
- src/ol_openedx_rapid_response_reports/templates/rapid_response.html
- src/ol_openedx_rapid_response_reports/urls.py
https://github.com/mitodl/open-edx-plugins/issues/230
- Removes deprecated/removed functionality from old Django 3.x
- Support for 4.x
-  Package geenration should be successful
- Everything should work with Quince release of edX
> chore: support django 4.x

- .github/workflows/ci.yml
- src/ol_openedx_course_export/README.rst
https://github.com/mitodl/open-edx-plugins/issues/334
Temporarily removes redwood from CI
See the CI logs
> fix: removed redwood from CI

- .pre-commit-config.yaml
- pants.toml
- poetry.lock
- pyproject.toml
- scripts/get-pants.sh
- src/edx_sysadmin/git_import.py
- src/edx_sysadmin/management/commands/tests/test_git_add_course.py
- src/edx_sysadmin/tests/test_sysadmin.py
- src/edx_sysadmin/utils/utils.py
- src/ol_openedx_rapid_response_reports/docs/conf.py
- src/ol_openedx_sentry/BUILD
- src/ol_openedx_sentry/settings/sentry.py
N/A
The latest releases of edX have addressed the infinite recursion bug that was being caused by Sentry, so this updates the Sentry SDK to the latest releases.
This also updates Pants to the latest stable version since it was out of date
Build the latest Sentry plugin and install in a version of edX >= Redwood and ensure that it doesn't cause an infinite recursion in the BulkEmail feature
> version: Update Sentry plugin to use SDK v2.x

- .github/workflows/ci.yml
- poetry.lock
- pyproject.toml
- run_devstack_integration_tests.sh
https://github.com/mitodl/hq/issues/4443
This PR replaces devstack with tutor in the CI for initializing edx-platform and running the integration tests of plugins. More details in the [ticket](https://github.com/mitodl/hq/issues/4443)
- Please see the CI job logs
- To test locally, try to follow the job steps from the CI on your local machine.( this will take a while to run )
- Build all the plugins packages using `pants build ::`
- install tutor:
- Nightly for Master Branch
```
git clone --branch=nightly https://github.com/overhangio/tutor.git
pip install -e "./tutor"
```
- For Quince branch `pip install tutor==17.0.6`
- For Redwood branch `pip install tutor==18.0.0`
- Go to edx-platform directory and run `tutor mounts add .`
- Build tutor images by running `tutor images build …
> Added Tutor in CI

- .github/workflows/ci.yml
- run_devstack_integration_tests.sh
- src/edx_sysadmin/git_import.py
- src/ol_openedx_chat/urls.py
Closes https://github.com/mitodl/hq/issues/6086
CI was failing after the merge of https://github.com/overhangio/tutor/commit/a666732f1ad7368f3b6a391a2b1c7c1783df3b4b. This PR removes python 3.8 from CI.
Note: edx-platform is also running tests only on python 3.11
Verify that all the checks are passing and all the tests are running
> fix: failing CI tests

- src/ol_social_auth/README.rst
- src/ol_social_auth/backends.py
- src/ol_social_auth/tests/backends_test.py
- src/openedx_companion_auth/settings/common.py
- src/openedx_companion_auth/settings/test.py
- src/openedx_companion_auth/tests/middleware_test.py
First step of https://github.com/mitodl/hq/issues/5726#issuecomment-2416510876
This PR updates the backend class name in `ol-social-auth` plugin to `OLOAuth2` and backend name to `ol-oauth2`. Additionally, it also updates `MITX_REDIRECT_LOGIN_URL` in openedx-companion-auth
Follow the steps in https://github.com/mitodl/hq/issues/5726#issuecomment-2416510876 for local setup
> feat: change backend name of social auth

- src/openedx_companion_auth/BUILD
None
https://github.com/mitodl/open-edx-plugins/commit/0fd7824c306b5a654003ca9721a08d39b699920a has been merged recently but the openedx-companion-auth version was not updated. This PR updates the openedx-companion-auth version to `1.1.0`
- Run `pants package ::` and verify that the package is created with version `1.1.0`
> chore: update companion-auth version

- src/edx_username_changer/README.rst
- src/ol_openedx_canvas_integration/README.rst
- src/ol_openedx_chat/README.rst
- src/ol_openedx_checkout_external/README.rst
- src/ol_openedx_course_export/README.rst
- src/ol_openedx_course_structure_api/README.rst
- src/ol_openedx_otel_monitoring/README.rst
- src/ol_openedx_rapid_response_reports/README.rst
- src/ol_social_auth/README.rst
- src/openedx_companion_auth/README.rst
- src/rapid_response_xblock/README.rst
#22 
This PR fixes a typography error made in #435 . Key changes include:
1. Updates child README.rst files to remove `` at the end of this line `For detailed installation instructions, please refer to the plugin installation guide.`
- Navigate to any plugin in the src directory
- Verify that no `` are present after this line `For detailed installation instructions, please refer to the plugin installation guide.`
- Verify that the relative link to central installation guide works
> docs: typo fix on individual plugin docs

- src/ol_openedx_chat/BUILD
- src/ol_openedx_chat/block.py
- src/ol_openedx_chat/compat.py
Closes https://github.com/mitodl/hq/issues/6825
Adds a waffle flag ol_openedx_chat.ol_openedx_chat_enabled to enable ol_openedx_chat for a single course.
When the waffle flag is enabled for a course:
When the waffle flag is not enabled for the course:
- Generate package by checking out this branch and running `pants package :: .`
- Enable xBlock configurations in CMS <STUDIO_URL>/admin/xblock_config/studioconfig/
- Enable xBlock asides in LMS <LMS_URL>/admin/lms_xblock/xblockasidesconfig/
- Install the ol-openedx-chat in LMS and CMS, Reload them
- In frontend-app-learning:
- Create env.config.jsx and add the below code:
```
import * as remoteAiChatDrawer from "./mitodl-smoot-design/dist/bundles/remoteAiChatDrawer.umd.js"
remoteAiChatDrawer.init({
messageOrigin: …
```
> feat: add OL_OPENEDX_CHAT_ENABLED flag

- src/ol_openedx_chat/block.py
- src/ol_openedx_chat/static/html/studio_view.html
- src/ol_openedx_chat/static/js/ai_chat.js
- src/ol_openedx_chat/static/js/studio.js
Closes https://github.com/mitodl/hq/issues/6838
Removes extra config fields from the CMS for the AI Assistant.
- Generate package by checking out this branch and running `pants package :: .`
- Enable xBlock configurations in CMS <STUDIO_URL>/admin/xblock_config/studioconfig/
- Enable xBlock asides in LMS <LMS_URL>/admin/lms_xblock/xblockasidesconfig/
- Install the ol-openedx-chat in LMS and CMS, Reload them
- In frontend-app-learning:
- Create env.config.jsx and add the below code:
```
import * as remoteAiChatDrawer from "./mitodl-smoot-design/dist/bundles/remoteAiChatDrawer.umd.js"
remoteAiChatDrawer.init({
messageOrigin: "http://local.openedx.io:8000",
transformBody: messages => ({ message: messages[messages.length - 1].content }),
})
const config = {
...process.env,
};
export default …
```
> feat: remove extra ai assistant config fields

- src/ol_openedx_chat/BUILD
- src/ol_openedx_chat/block.py
- src/ol_openedx_chat/constants.py
- src/ol_openedx_chat/static/html/student_view.html
- src/ol_openedx_chat/static/js/ai_chat.js
Closes https://github.com/mitodl/hq/issues/6843
Passes the block usage key and transcripts asset ID.
Here are the example block usage keys:
```
Video: block-v1:testx+test101+2024_T1+type@video+block@d6d49d1d72f942cd9d534a54f99d8a87
Dropdown: block-v1:testx+test101+2024_T1+type@problem+block@a5e043d9325e4ed9b8912d1131051321
MCQ: block-v1:testx+test101+2024_T1+type@problem+block@be69872810904ad195e8ec9241a59e5d
```
Here is an example Asset ID for the video block English transcript:
`asset-v1:testx+test101+2024_T1+type@asset+block@91204cd0-44cb-4b68-9e44-303ff8ffc2e3-en.srt`
- Generate package by checking out this branch and running `pants package :: .`
- Enable xBlock configurations in CMS <STUDIO_URL>/admin/xblock_config/studioconfig/
- Enable xBlock asides in LMS …
> feat: add block usage key and transcript asset id

- src/ol_openedx_chat/BUILD
- src/ol_openedx_chat/static/css/studio.css
- src/ol_openedx_chat/static/html/studio_view.html
- src/ol_openedx_chat/static/js/studio.js
Closes https://github.com/mitodl/hq/issues/6814
Enables Unit publish when AI Chat is enabled or disabled. Also, removes the save button and relies on the checkbox to enable/disable.
https://github.com/user-attachments/assets/b3878677-5037-4961-a03d-80e22c25a42b
- Generate package by checking out this branch and running `pants package :: .`
- Enable xBlock configurations in CMS <STUDIO_URL>/admin/xblock_config/studioconfig/
- Enable xBlock asides in LMS <LMS_URL>/admin/lms_xblock/xblockasidesconfig/
- Install the ol-openedx-chat in LMS and CMS, Reload them
- make sure to install the latest version 0.2.4
- In frontend-app-learning:
- Create env.config.jsx and add the below code:
```
import * as remoteAiChatDrawer from "./mitodl-smoot-design/dist/bundles/remoteAiChatDrawer.umd.js" …
```
> feat: enable unit publish when ai chat is enabled/disabled

- src/ol_openedx_chat/BUILD
- src/ol_openedx_chat/block.py
- src/ol_openedx_chat/constants.py
- src/ol_openedx_chat/static/js/ai_chat.js
None
Adds chat API URL based on the block type.
- Setup ol-openedx-chat by following the [readme](https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_chat).
- Now enable AI Chat for a video and problem block.
- Go to the LMS and verify that for video block the chat request is sent to `<LEARN_AI_API_URL>/http/video_gpt_agent/` and for problem block, it is sent to `<LEARN_AI_API_URL>/http/tutor_agent/`
> feat: add different chat URLs for video and problems

- src/ol_openedx_chat/BUILD
- src/ol_openedx_chat/block.py
- src/ol_openedx_chat/static/js/ai_chat.js
None
Passes block type to the AI Chat drawer.
- Setup by following the [Readme](https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_chat).
- You can add console log in ai_chat.js to see what is available in event.data.blockType.
> feat: pass block type to chat drawer

- src/ol_openedx_chat/BUILD
- src/ol_openedx_chat/README.rst
- src/ol_openedx_chat/block.py
- src/ol_openedx_chat/constants.py
- src/ol_openedx_chat/settings/common.py
- src/ol_openedx_chat/settings/devstack.py
- src/ol_openedx_chat/static/js/ai_chat.js
A part of https://github.com/mitodl/hq/issues/6985
- Updates the drawer payload structure as per the drawer requirements.
- Adds a new setting MIT_LEARN_API_BASE_URL and renames `LEARN_AI_API_URL` to `MIT_ LEARN_AI_API_URL`.
- Also, add another setting for the video summary and flashcards to point to the API URL named `MIT_LEARN_SUMMARY_FLASHCARD_URL`
- Follow the [updated readme](https://github.com/mitodl/open-edx-plugins/blob/4e66a20aaef5eceb710e0d0daf52ebc47c8a3e88/src/ol_openedx_chat/README.rst) from this PR to setup ol_openedx_chat.
- You can add a console log statement in ai_chat.js to see the payload.
- Verify that the drawer is working when enabled.
- Verify that chatting with a Problem block sends the expected request body by monitoring the network. It should have block_siblings. …
> feat: update drawer payload

- src/ol_openedx_chat/BUILD
- src/ol_openedx_chat/README.rst
- src/ol_openedx_chat/block.py
For https://github.com/mitodl/hq/issues/6985
This updates the plugin to send `AskTIM` in the title, which is what v6 of smoot-design wants.
1. Run the plugin locally, following directions in `src/ol_openedx_chat/README.rst` In particular, use v6 of smoot-design
2. View a problem and video with tutor enabled. Observe that the title shows up correctly on all video tabs and in the tutor drawer.
- **NOTE:** If you actually want to see content in the drawer for the video, probably the easiest thing is to change the `content_url` value in `block.py` to be a static value like `"https://api.rc.learn.mit.edu/learn/api/v1/contentfiles/?edx_module_id=asset-v1%3AMITxT%2B3.012Sx%2B3T2024%2Btype%40asset%2Bblock%400cc53e11-1f91-4ed8-8bab-0d873db8cb90-en.srt"`
> display title in v6 smoot-design drawer

- src/ol_openedx_chat/BUILD
- src/ol_openedx_chat/tests/test_aside.py
- src/ol_openedx_chat/tests/test_utils.py
- src/ol_openedx_chat/tests/utils.py
- src/ol_openedx_chat/utils.py
A part of https://github.com/mitodl/hq/issues/4987#issuecomment-2775751816
Fixes an issue with the course import, during course import the course key is in the format `{org}/{course_code}/{run_code}`. This results in no course found when we get the course from modulestore to check the advanced settings.
Course import generates the old format key explicitly as explained in [get_id](https://github.com/openedx/edx-platform/blob/master/xmodule/modulestore/xml.py#L597) docs and comment.
- Checkout main branch Install the ol_openedx_chat plugin by following the [ReadME](https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_chat). Install the latest 0.3.2 version.
- Now create a course with a few videos, and different problem types. Also, enable `Enable AI Chat Assistant` for a few …
> fix: recreate course key during course import

- src/ol_openedx_chat/BUILD
- src/ol_openedx_chat/block.py
- src/ol_openedx_chat/tests/test_aside.py
- src/ol_openedx_chat/tests/test_utils.py
- src/ol_openedx_chat/utils.py
https://github.com/mitodl/hq/issues/7076
Do not check for course settings and waffle flag during XML course import.
- Setup by following the readme
- end-to-end test course import and export.
- Course import and export should import all blocks and should retain the state for `Enable AI Chat Assistant`
- Test for different course run keys.
- Export a course from QA and import locally, it should work.
For Video Asides, you can checkout the following branch https://github.com/openedx/edx-platform/pull/36500. Otherwise, it won't retain the state for the Video blocks.
> fix: should apply only checks for block type during course import

- src/ol_openedx_git_auto_export/BUILD
- src/ol_openedx_git_auto_export/settings/common.py
- src/ol_openedx_git_auto_export/settings/production.py
- src/ol_openedx_git_auto_export/signals.py
- src/ol_openedx_git_auto_export/tasks.py
https://github.com/mitodl/hq/issues/6803
This PR:
1. Start course export on publish only when giturl exists
1. Checkout to this branch
2. Create installable package by following the instructions in [Readme file](https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_git_auto_export)
3. Install the package in edX.
4. Create a course in studio and make sure giturl value is set to empty or null in course advance settings
5. Publish the course
6. Keep an eye on logs -- you should see `Course {course_key} does not have a giturl, skipping export.` instead of error saying `'NoneType' object has no attribute 'endswith'`
> fix(git-auto-export): Start export only if GIT_URL exists in the course settings

- src/edx_sysadmin/BUILD
- src/edx_sysadmin/api/views.py
https://github.com/mitodl/ol-infrastructure/issues/2891#issuecomment-2855121735
This PR:
1. Logs exception only when necessary
1. Checkout to this branch
2. Create installable package by following the instructions in [Readme file](https://github.com/mitodl/open-edx-plugins/tree/main/src/edx_sysadmin)
3. Install the package in edX
4. Make sure you have setup the hook for course auto reload
5. Change the default branch setting for this plugin to something different. For example: `dummy`
6. Publish any course from studio without any change which will invoke the hook for edx_sysadmin > gitreload OR directly push changes to github repo whose hook is configured
7. Verify that there are debug logs like `Couldn't reload course for the branch` instead of exception
> chore(edx-sysadmin): Improve logging when incoming branch conflicts with setting branch

- src/ol_openedx_course_sync/BUILD
- src/ol_openedx_course_sync/tasks.py
- src/ol_openedx_course_sync/tests/test_tasks.py
Closes https://github.com/mitodl/hq/issues/7523
Fixes a bug with the course sync plugin to copy the course assets.
- Setup course sync plugin by following the [readme](https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_course_sync)
- Now add assets in the source course and publish the course. The assets should get copied to the target/rerun courses.
> fix: copy course assets on publish

- src/ol_openedx_chat/BUILD
- src/ol_openedx_chat/block.py
- src/ol_openedx_chat/static/js/ai_chat.js
- src/ol_openedx_chat/tests/test_aside.py
https://github.com/mitodl/hq/issues/7632
Adds event tracking backend for the tutor plugin
- Setup chat plugin by following the [readme](https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_chat)
- Now follow the testing instructions in https://github.com/mitodl/smoot-design/pull/139. Do update the Learning MFE env.config.jsx
- Now test that chat drawer events like open, close, submit, tabchange are logged in lms logs.
Sample Log for Drawer Open:
```
lms-1          | 2025-07-02 09:25:33,914 INFO 524 [tracking] [user 4] [ip 192.168.65.1] logger.py:41 - {"name": "ol_openedx_chat.drawer.open", "context": {"course_id": "course-v1:TDT+TDT101+R3", "course_user_tags": {}, "user_id": 4, "path": "/courses/course-v1:TDT+TDT101+R3/xblock/aside-usage-v2:block-v1$:TDT+TDT101+R3+type@probl …
```
> feat: add tracking logs

- src/ol_openedx_chat_xblock/ol_openedx_chat_xblock/static/css/ai_chat_xblock.css
- src/ol_openedx_chat_xblock/pyproject.toml
Closes https://github.com/mitodl/hq/issues/7849
Increases height of canvas chat ui.
**In Canvas:** (Manually edited the existing CSS—i.e., not actually this version—but the canvas view is what matters.)
**In MFE LMS**:
**In Legacy Studio:**
1. Enable the xblock locally; view it in LMS and CMS.
@asadali145 I had trouble enabling this locally. So I actually haven't tested it locally.  I added `["ol_openedx_chat_xblock"]` to the advanced module list.
Do I need a waffle flag?
**Edit:** Resolved; tested it locally now.
> increase chat height

- src/ol_openedx_chat/README.rst
- src/ol_openedx_chat_xblock/ol_openedx_chat_xblock/static/js/lms.js
- src/ol_openedx_chat_xblock/ol_openedx_chat_xblock/static/js/studio.js
Related to https://github.com/mitodl/smoot-design/pull/167 and https://github.com/mitodl/learn-ai/pull/276
Updates smoot-design to the latest version, which properly formats any chatbot citation links that might be in AI responses (primarily for the syllabus bots).
- Tests should pass.
- Ask a question in the syllabus chat xBlock like:
` What is this course about? Please provide a link to the course in the format "[^🔗^](course_url)"`
-  The answer should include a link to the course that looks something like this:
See https://github.com/mitodl/smoot-design/pull/167 and https://github.com/mitodl/learn-ai/pull/276
> Update smoot-design version

- src/ol_openedx_course_export/ol_openedx_course_export/views.py
https://github.com/mitodl/hq/issues/8223
This PR adds the code to return `PENDING` state when `UserTaskStatus` is not yet created. This avoids the code from breaking while accessing the status from the object, which doesn't exist yet. More details in the linked issue.
- To test this, we need to use tutor local to run the celery workers.
- First, create a tutor-plugin for settings. I tried other approaches as well, such as adding directly to the production.py file and also trying to add it to the config.yml file, but they didn't work. Run the commands below:
- First create a plugins file in the plugin root: 
```
cd "$(tutor plugins printroot)"
touch myplugin.py
```
- Next, paste the following code in the file:
```python
from tutor import hooks
hooks.Filters.ENV_PATCHES.add_item(
( …
```
> fix: return NOT FOUND state when UserTaskStatus is not yet created

- src/rapid_response_xblock/pyproject.toml
- src/rapid_response_xblock/rapid_response_xblock/static/js/src_js/rapid_studio.js
https://github.com/mitodl/hq/issues/8113
Trigger postmessage to authoring MFE to enable the publish button in the sidebar when rapid response state changes.
- Setup following the readme
- Enable authoring MFE unit page
- Add single select problem
- Change rapid response state and see that the publish button is enabled.
> fix: send postmessage to authoring MFE to update publish btn for rapid response
